name: mdl_gen

channels:
  - pytorch
  - conda-forge

dependencies:
  - python==3.11.9
  - conda-forge::pandas==2.1.2
  - conda-forge::scikit-learn==1.3.2
  - conda-forge::seaborn==0.13.1
  - conda-forge::jupyterlab==4.0.8
  - pytorch==2.5.1
  - torchvision==0.20.1
  - conda-forge::pytorch-lightning==2.1.0
  - conda-forge::torchmetrics==1.2.0
  - conda-forge::python-dotenv==1.0.1
  - conda-forge::gdown==5.2.0
  - conda-forge::datasets==2.14.6
  - conda-forge::scikit-image==0.20.0